project: dabi_net_paper_release
task: Breast ultrasound binary classification (single-modal and multimodal)

dataset_config: configs/dataset/breast_ultrasound_binary.yaml
default_method: dabi_net

methods:
  dabi_net: configs/methods/dabi_net.yaml
  resnet18: configs/methods/resnet18.yaml
  vit_b: configs/methods/vit_b.yaml
  convnext_b: configs/methods/convnext_b.yaml
  sw_forknet: configs/methods/sw_forknet.yaml
  hovertrans: configs/methods/hovertrans.yaml
  mb_dcnn: configs/methods/mb_dcnn.yaml
  cam_qus: configs/methods/cam_qus.yaml
  msgof: configs/methods/msgof.yaml
  mup_net: configs/methods/mup_net.yaml
  tdf_net: configs/methods/tdf_net.yaml
  mvmm: configs/methods/mvmm.yaml

archived_configs:
  dabi_net: configs/original/dabi_net_paper_config.yaml
  resnet18: configs/original/resnet18_paper_config.yaml
  vit_b: configs/original/vit_b_paper_config.yaml
  convnext_b: configs/original/convnext_b_paper_config.yaml
  sw_forknet: configs/original/sw_forknet_paper_config.yaml
  hovertrans: configs/original/hovertrans_paper_config.yaml
  mb_dcnn: configs/original/mb_dcnn_paper_config.yaml
  cam_qus: configs/original/cam_qus_paper_config.yaml
  msgof: configs/original/msgof_paper_config.yaml
  mup_net: configs/original/mup_net_paper_config.yaml
  tdf_net: configs/original/tdf_net_paper_config.yaml
  mvmm: configs/original/mvmm_paper_config.yaml
